### ISSUE TITLE
Are there any solutions to the excercises?

### ISSUE THREAD

**Issue by bytesource** [Zaid-Ajaj/elmish-hackernews-part3#2]
Hi Zaid, 

I love your book and I have been following every line of code so far on my computer. 

I'm currently doing the HN exercises, and it would be great if there were some reference solutions, but there's no link in the text. 

Are there any solutions to these exercises?

Cheers, 

Stefan

**Comment by Zaid-Ajaj** [comment]
Hi Stefan, I am happy to hear you are enjoying the book!

Unfortunately for the hacker news exercises, there are currently no reference solutions. However, I would be happy to review your solution or help you along the way to come up with one 😄

**Comment by bytesource** [comment]
Hi Zaid,

Thanks, that's very generous of you! 

I finished the first exercise, and it seems to be working: https://github.com/bytesource/Elmish-Hackernews-Exercises/blob/HN3-EX1/src/App.fs#L403

It would be great if you could take a brief look at it. As I don't have a programming background, I'm especially interested in how to improve my code with regard to best practices.

**Comment by Zaid-Ajaj** [comment]
The code looks good all in all :100: 

There a couple of minor things: my idea was to refactor the `HackernewsItem` type and the make the `Published` field be of type `DateTime` rather than `int64`. I see you already have a function to convert between the two which means with a little bit of `Decode.map` magic you can change the type to 
```fs
type HackerNewsItem = {
    Id: int
    Title: string
    Url: string option
    Score: int
    // Published: int64
    Published : DateTime
}
```
Once you have this type in place, it makes it easy to work with and to format to a human-readable text (i.e 25 May).

Another thing is that you don't really need to `List.partition` the items after sorting:
```fs
        let resolvedItems, remainingItems =
            storyItems
            |> Map.toList
            |> List.sortBy (fun (_, item) -> // Sort by publish date
                match item with
                | Resolved (Ok post) -> post.Published
                | _ -> toUnixTimeSeconds(DateTime.Now)) // Current Unix timestamp. Always larger than timestamp at 'Published'.
            |> List.partition (fun (_, item) -> // Partition out sucessfully loaded posts
                match item with
                | Resolved (Ok post) -> true
                | _ -> false)
```
Sorting should be enough because you already put the resolved items on top.

if you have any questions just let me know 😉

**Comment by bytesource** [comment]
Hi Zaid, 

Thanks for your feedback!

First, I changed the type of the `Published` field to `DateTime` and fixed all compiler errors. 

Then I realized that my sorting was not correct, as you required the most _recent_ posts to appear at the top. So I replaced `List.sortBy` with `List.sortByDescending`.

Unfortunately, this meant that now `Resolved` items would appear _after_ all other items. This is why I still went with `List.participate`. Not sure if this is the best approach.

Final solution: https://github.com/bytesource/Elmish-Hackernews-Exercises/blob/master/src/App.fs#L397

Again, thanks a lot for your help!

**Comment by Zaid-Ajaj** [comment]
> Then I realized that my sorting was not correct, as you required the most recent posts to appear at the top. So I replaced List.sortBy with List.sortByDescending.
Unfortunately, this meant that now Resolved items would appear after all other items. This is why I still went with List.participate. Not sure if this is the best approach.

I think the `Resolved` items are appearing after the non-resolved ones because you use `DateTime.Now` as a default value when an item has not been resolved. This makes them appear first as they are the "most recent future". You can use `DateTime.MinValue` as a default value when you `List.sortByDescending` which puts them way the end of the list:
```fs
storyItems 
|> Map.toList
|> List.sortByDescending (fun (_, item) ->
      match item with
      | Resolved (Ok post) -> post.Published
      | _ -> DateTime.MinValue)
```

**Comment by bytesource** [comment]
I didn't know about `DateTime.MinValue`. This makes for a very elegant solution. 

Thanks for the tip!

**Comment by Zaid-Ajaj** [comment]
No problem! Happy to help :smile:

> It looks like not having solutions to the exercises (much like your daily requirements IRL) makes you research all the possible options which I really like.

**Comment by bytesource** [comment]
Hi Zaid, 

I hope you don't mind me posting on a closed issue. 

It's just that I just finished exercise 3 and it would be great if you could to take a look my solution, especially for this reason:

You suggested using `int * AsyncOperationStatus<Result<HackernewsItem, string>>` as the type for the `LoadedStoryItem` message, but I couldn't find a way to apply your recommendation in my code.

To be fair, the proper usage of `Deferred` in combination with `AsyncOperationStatus` (and when to use which) has been the biggest hurdle so far. But I think it just takes some time and practice until dealing with more complicated becomes second nature.

That said, I still managed to code up a solution and I haven't found any bugs so far. 

It would mean a lot to me if you could give me some very honest feedback on how I could improve this code with regards to best pratices in F# and Elmish: https://github.com/bytesource/Elmish-Hackernews-Exercises/blob/master/src/App.fs

Best regards,

Stefan
